export const ROUTE_COMPONENTS_HOME = 'ROUTE_COMPONENTS_HOME';
export const ROUTE_AVATARS = 'ROUTE_AVATARS';
export const ROUTE_BUTTON = 'ROUTE_BUTTON';
export const ROUTE_LIST_ITEM = 'ROUTE_LIST_ITEM';
export const ROUTE_SPINNERS = 'ROUTE_SPINNERS';
